### ISSUE TITLE
Any chance of a tag/stable version of this?

### ISSUE THREAD

**Issue by mlewis-everley** [axllent/silverstripe-scaled-uploads#2]
Love the module, but I am trying to switch to using only stable versions, would it be poss to push a tag up?

Cheers,

Mo

**Comment by axllent** [comment]
Sure thing Mo, there haven't been any code changes in ages so I'd say it's safe to assume it's stable :)

v1.0 released...

**Comment by mlewis-everley** [comment]
Cool, cheers! I would say you are right :-)
