### ISSUE TITLE
Enhancement: Scale images in browser before upload

### ISSUE THREAD

**Issue by wernerkrauss** [axllent/silverstripe-scaled-uploads#3]
Any chance to get e.g.g UploadField resizing the image before uploading to the server? This would overcome memory issues when uploading way too big images...

**Comment by axllent** [comment]
Whilst I understand your idea, that is really a separate project entirely entirely as it focuses on the front-end (client-side). I have used [plupload](http://plupload.com/) in another project (not SilverStripe) before, so I know that it is possible to scale images client-side (although it too has some [limitations](http://plupload.com/docs/Image-Resizing-on-Client-Side#limitations) which also cause memory issues client side).

I think that for SilverStripe it would mean rewriting the entire UploadField functionality, or creating a whole new type of "upload field" (probably a better idea). Either way though, it's not going to happen in this project as this is a "back-end" plug-and-play module.
