### ISSUE TITLE
Doesn't work in Silverstripe 4.1

### ISSUE THREAD

**Issue by andreaslindahl** [axllent/silverstripe-scaled-uploads#7]
I can't get this to work in Silverstripe 4.1 - no scaling is done when images are uploaded. I installed using composer and have added the scaled-uploads.yml with the required settings. Is there anything else I need to do?

**Comment by axllent** [comment]
Hi @andreaslindahl. I can confirm that it does work as expected in SilverStripe 4.1. There could be a couple of reasons yours isn't working.

1. Did you `?flush` after you installed the module?
2. Is the image you are uploading maybe too big for PHP to process? Depending on your available PHP memory, PHP may be segfaulting when trying to process the image. Your webserver error logs should be able to confirm if that is the case. Image processing costs a lot of RAM in any situation, and if yours is set very low (eg: 128MB) then you're going to get issues generally speaking if you are uploading images that are (for example) 6000px.

Please let me know if this helps?

**Comment by andreaslindahl** [comment]
I don't know why, but it suddently started to work. I did a couple of flushes after installing it, which didn't help. Anyway, it's working now. :)
