### ISSUE TITLE
Image dimensions (width or height) are empty before storing

### ISSUE THREAD

**Issue by lhasselb** [axllent/silverstripe-scaled-uploads#8]
Hi,

first thank you for that nice module.
This issue is related to 1.0.2 for SS3, so you may not care (I didn't test on 4 yet). 
It seems that some update within 3.x changed the ability to get the image dimensions
like $this->owner->getHeight() or $this->owner->getWidth() before an image is stored.
Therefore the initial "if" check whether to scale or not fails.

Cheers 
Lars

**Comment by axllent** [comment]
Hi there!

Firstly of course I do care ;-) I still use SS3 on many sites and this module is installed on almost every one. I have tested here and cannot replicate the issue anywhere - it works exactly as expected (v1.0.2 on SS 3.7.1).

Are you getting an actual error somewhere, or is it just not working? It could be that your system simply cannot scale any images because it can't read them.

Please confirm?

Cheers,
Ralph

**Comment by lhasselb** [comment]
Thanks for the quick response and that you still care :-)

The whole story on my side:
I have a site (SS 3.7.1) running v1.0.2 with the following config:

`# Rescale upload to max-width/-height
ScaledUploads:
  max-width: 1600
  max-height: 1200
  auto-rotate: 0
  bypass: 0 `

Some days ago a content editor start complaining 
about incorrect size of uploaded images so I added some logging to
the  ScaledUploads module to verify the values within

`
        if (
            $this->owner->getHeight() > $this->getMaxHeight()
            || $this->owner->getWidth() > $this->getMaxWidth()
            || ($this->getAutoRotate() && preg_match('/jpe?g/i', $extension))
        )
`
and I was not able to get a value for $this->owner->getHeight() or $this->owner->getWidth() 

After that I thought this might be caused due to some API changes so I changed the initialization from
onBeforeWrite to onAfterWrite.
The values were accessible after that.

Sorry for the confusion but that seems like a issue to me.
Any idea about that ?

Thanks again
Lars

**Comment by axllent** [comment]
Thanks for reporting back Lars.

I'm still confused though. Are you saying that your uploaded image was bigger thank your defined sizes, but because you had `auto-rotate: 0` set you got an error? If so, please tell me the exact error (you may need to refer to your php log or your browser's debug tool).

I'm asking because if there is a related bug then I need to fix it.

Cheers,
Ralph

**Comment by lhasselb** [comment]
Sorry for been nebulous ;-)

First: No there is no error message.

I just tried to point out that the config setting
`auto-rotate: 0` act like using 
`bypass: true `
because of 
`if (`
`$this->owner->getHeight() > $this->getMaxHeight()`
`|| $this->owner->getWidth() > $this->getMaxWidth()`
`|| ($this->getAutoRotate() && preg_match('/jpe?g/i', $extension))`
`)`
because the function getAutoRotate() delivers **false** for `auto-rotate: 0`

**Comment by lhasselb** [comment]
Your summary perfectly makes sense.
The image was bigger than 1600x1200, uploaded but not touched by the resize logic.
So SS did not report any error. No need to be worried.

About 
3. OR auto-rotate is true AND it is a jpg file
with auto-rotate: 0  the scaling will not start. 
Is it meant like that ?

**Comment by axllent** [comment]
No, if auto-rotate is disabled then it should still scale the image down. Please leave this open and I will investigate soon.

Thanks again for your feedback.

**Comment by axllent** [comment]
@lhasselb So you were completely correct. With more investigation I also came to the conclusion that the `$this->owner->getWidth()` & `$this->owner->getHeight()` weren't actually returning anything. Actually the only reason the function was working for most people was if `auto-rotate` was true, which is default and so was never noticed.

I have written a fix for this and published it in the latest 1.* release. If you get some time please confirm that it does work as expected for you? Thanks again!

**Comment by lhasselb** [comment]
Hereby confirmed (tested with auto_rotate = true/false and images > default).
