### ISSUE TITLE
Uploads to fail with legacy_filenames: true

### ISSUE THREAD

**Issue by purplespider** [axllent/silverstripe-scaled-uploads#9]
If you have `legacy_filenames: true` set on `SilverStripe\Assets\Flysystem\FlysystemAssetStore` in order for WYSIWYG images and file links to still work after migrating a SilverStripe 3 site to SilverStripe 4, this module fails to work, it causes any uploads to fail. The DO is created, but the file isn't uploaded resulting in "File Not Found".

**Comment by axllent** [comment]
Good catch! Actually the file is uploaded, however there is an extra step in there for the `FlysystemAssetStore` that deletes the original (after manipulation) to prevent stray originals being left in `assets` (as they get a new hash after manipulation, thus different location). When using the Legacy file system this deletes the file that is supposed to be overwritten (ie: the path stays the same), and it fails.

I'll releasing a new version shortly that checks for the use of `legacy_filenames`.
